import Head from 'next/head';
import { useState, useEffect } from 'react';

function getData(setData) {
    const api_url = process.env.NEXT_PUBLIC_API_URL + '/business';

    fetch(api_url, {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
    })
        .then((res) => {
            try {
                const data = res.json();
                return data;
            } catch (err) {
                console.log(err);
            }
        })
        .then((data) => {
            setData(data);
        })
        .catch((err) => {
            console.log(err);
        });
}

export default function Home() {
    const [data, setData] = useState([]);

    useEffect(() => {
        getData(setData);
    }, []);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>

            <h1 className="text-3xl font-bold">Next tailwind amazona</h1>

            {data.map((item) => {
                return (
                    <div key={item._id}>
                        <h1>{item.name}</h1>
                        <p>{item.city}</p>
                        <p>{item.address}</p>
                    </div>
                );
            })}
        </div>
    );
}
